### ISSUE TITLE
Environment.py can't compile?

### ISSUE THREAD

**Issue by magicorder** [cmitash/physics-scene-rendering-vision#3]
python -m Environment.py
/usr/bin/python: No module named bpy

and

python generate_pictures.py 
/home/huichang/blender-2.78c/blender blank.blend -b --python simulate_and_render.py
found bundled python: /home/huichang/blender-2.78c/2.78/python
read blend: /home/huichang/mydata/physim-dataset-generator/blank.blend
Traceback (most recent call last):
  File "/home/huichang/mydata/physim-dataset-generator/simulate_and_render.py", line 21, in <module>
    from Environment import Shelf, Table, Light
ImportError: No module named 'Environment'

Blender quit

why Environment.py can't compile to Environment.pyc

**Comment by magicorder** [comment]
if run blender blank.blend -b --python Environment.py, i can get Environment.pyc, but run "blender blank.blend -b --python simulate_and_render.py" again, i got the some error:
found bundled python: /home/huichang/blender-2.78c/2.78/python
read blend: /home/huichang/mydata/physim-dataset-generator/blank.blend
Traceback (most recent call last):
File "/home/huichang/mydata/physim-dataset-generator/simulate_and_render.py", line 21, in 
from Environment import Shelf, Table, Light
ImportError: No module named 'Environment'

Blender quit

**Comment by magicorder** [comment]
copy import*.py files to /path/to/blender/2.78/scripts/startup/ sovle it!!
将引入的所有包，放在blender安装目录下的startup文件夹中，解决问题！
